import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import React from 'react';
import Image from 'next/image';
import { Button } from "@/components/ui/button";
import { Menu, Settings, User } from "lucide-react";
import { Sidebar } from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Background Image */}
        <div className="fixed inset-0 -z-10">
          <Image
            src={'/images/body-background.webp'}
            alt="Background"
            fill
            priority
            className="object-cover"
            quality={100}
          />
          {/* Dark overlay */}
          {/* <div className="absolute inset-0 bg-[#0A0A29]/90 backdrop-blur-sm" /> */}
        </div>

        <div className="min-h-screen flex relative z-0">
          {/* Sidebar with glass effect */}
          <div className="relative">
            <div className="" />
            <Sidebar />
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col px-6 pt-4 ">
            {/* Top Navigation with glass effect */}
            <header className="h-16 flex items-center  justify-between px-6 relative">
              <div className="absolute inset-0 bg-[#0A0A29]/30 rounded-xl backdrop-blur-sm -z-10" />
              <div className="flex items-center z-10">
                <Button variant="ghost" size="icon" className="text-gray-400 hover:text-white">
                  <Menu className="h-5 w-5" />
                </Button>
              </div>
              
              <div className="flex items-center space-x-4 z-10">
                <Button size="icon" variant="ghost" className="text-gray-400 hover:text-white">
                  <Settings className="h-5 w-5" />
                </Button>
                
                <Button size="icon" variant="ghost" className="text-gray-400 hover:text-white">
                  <User className="h-5 w-5" />
                </Button>
              </div>
            </header>

            {/* Page Content */}
            <main className="flex-1 overflow-y-auto pt-6">
              {/* Content wrapper with glass effect */}
              <div className="relative rounded-lg">
                <div className="absolute inset-0 bg-[#0A0A29]/30 backdrop-blur-sm -z-10 rounded-lg" />
                <div className="relative z-0">
                  {children}
                </div>
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}